### ISSUE TITLE
#110 should increment package version

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#114]
#110 having significant new functionality, we should increment package version to 0.0.9.

**Comment by tibetsprague** [comment]
I would be good to agree on a policy of when to increment the version and to what

**Comment by dkent600** [comment]
http://semver.org/

**Comment by dkent600** [comment]
One question can be:  at what version should we consider ourselves to be now?  Perhaps there should be a "-alpha" (or even less) appended?

**Comment by leviadam** [comment]
I think the suggested policy by @dkent600 is good.
But of course we are not yet ready to use it, as we are just starting, and backwards and things will break often. So alpha is a good solution.

**Comment by dkent600** [comment]
So "0.0.0-alpha.9" would be the current version?  Next version would be "0.0.0-alpha.10", where any new version would be assumed to be potentially breaking?

**Comment by tibetsprague** [comment]
I'm down with semver but @dkent600 to be clear that is not what we have been doing so far. For example you incremented the patch version for my latest changes but that was new functionality, not bug fixes, so really it should have been a new minor version. And I agree, we are not really public ready yet so an alpha version makes sense to me for now. Or sticking with semver and just knowing that all the 0.x.x versions indicate alpha.

**Comment by dkent600** [comment]
@tibetsprague Yes, I definitely didn't follow the suggested practice, precisely because it doesn't make much sense to do so right now, as Adam pointed out.

**Comment by leviadam** [comment]
OK, I think the suggestion to go with 0.0.0-alpha.x is good.
Agreed?
