### ISSUE TITLE
build more module types

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#115]
#110 introduced a build script that generates es2015 javascript modules to a dist folder.  That is great!  Now I recommend, to support more client needs, that we export more common module types and put them in sub folders, as follows:

dist/amd
dist/commonjs
dist/es2015
dist/native-modules
dist/system

**Comment by leviadam** [comment]
That sounds good, but we have to prioritize, how much work is that?

**Comment by dkent600** [comment]
I doubt it is much work at all.  However it is not immediately required.  I created this as a note that we should do this at some point as the world starts to discover Arc.

**Comment by dkent600** [comment]
This should be moved over to arc-js.
