### ISSUE TITLE
default user's gas limit is too high

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#119]
The default user's gas limit is too high.  As a result, the Alchemy user must enter a working value on approving every transaction against Kovan.

The value that is working for me is  4465000.

The value is configured in utils.js.

**Comment by leviadam** [comment]
The problem is that for some TXs we need more than that.

**Comment by dkent600** [comment]
@leviadam All I know is that this setting is working a heck of a lot better than the previous one.  I haven't yet encountered a problem with it.  Do you know what transactions are potentially a problem, and how much gas they will need?
