### ISSUE TITLE
Feature: Provide application a way to choose between kovan and mainnet contracts

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#124]
Right now applications using Arc have to use the set of Truffle artifact json files that are included in the Arc package.  But those files will have been generated only against either Kovan or the mainnet (or whatever).  

However applications may want to be able to use Kovan for testing and then mainnet for production, and specify to Arc which one they want to use.

But currently Arc has no way to enable applications to choose one set of contracts over the other.  We need to provide such capability to consuming applications.

This means shipping with more than one set of json contract files, minimum would be Kovan and mainnet.  Maybe Ropsten too, I don't know.

**Comment by tibetsprague** [comment]
This is something @leviadam and I have been discussing, and I am thinking through. But actually truffle handles this for you, when you deploy the contracts it is supposed to add the addresses of the deployment for that network to the list of networks at the bottom of the json file. So you can have the same compiled contract files with a list of all their addresses on all the networks they have been deployed to. We still need to test and confirm that this is working.

**Comment by tibetsprague** [comment]
Truffle should then know what network you are connecting too and look up the correct addresses for the current network. See http://truffleframework.com/docs/advanced/networks
