### ISSUE TITLE
utils.getValueFromLogs() crashes when tx.logs is empty

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#126]
`utils.getValueFromLogs()` crashes when `tx.logs` is empty (which happens on Kovan when `SimpleContributionScheme.submitContribution()` calls `getValueFromLogs(tx, '_proposalId')`.

It currently throws an exception that it can't access args from undefined.  Not helpful.

I will propose that it should throw an exception, but it should have a clear message, that "getValueFromLogs: Transaction has no logs".

**Comment by leviadam** [comment]
I guess this is fixed in the PR, so we can close this issue?
