### ISSUE TITLE
SchemeRegistrar supplies incorrect scheme permissions to controller

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#129]
When SchemeRegistrar registers a scheme with the controller, it does not always use the permissions that the scheme expects:

```
 if (proposal.isRegistering == false) {
        if (!controller.registerScheme(proposal.scheme, proposal.parametersHash, bytes4(1))) {
          revert();
        }
      } else {
        if (!controller.registerScheme(proposal.scheme, proposal.parametersHash, bytes4(3))) {
          revert();
        }
      }
```

For example, UpgradeScheme expects to have permission flags 9, but will only get 1 according to the above code. GlobalConstraintRegistrar expects 5, but will only get 1.

SchemeRegistrar should either hardcore all the cases properly, or better (I think), the desired permissions should be passed in as a new parameter to `proposeScheme`.

**Comment by dkent600** [comment]
@leviadam Can you please advise on the desired behavior here?  Thanks!

**Comment by leviadam** [comment]
Scheme register by itself usually will only have permission 3, so it can't give permission 5 or 9 anyway.

**Comment by dkent600** [comment]
How then is SchemeRegister to be expected to be able to create functional UpgradeSchemes or GlobalConstraintRegistrars ?

How can *any* scheme be able to do this?

If SchemeRegister is expected to have help with this, from where does the help come?

**Comment by leviadam** [comment]
It is not.
New global upgrade schemes will be approved using the upgrade scheme itself.

**Comment by dkent600** [comment]
@leviadam  This pertains not just to creating new schemes, but to modifying the parameters on the existing ones.  

What this means is that SchemeRegistrar will not be able to *modify* the existing params on UpgradeScheme or GlobalConstraintRegistrar.  Is that acceptable?

**Comment by leviadam** [comment]
Yes. I think this is how it should work.

**Comment by dkent600** [comment]
Does that mean that no changes are expected for the GlobalConstraintRegistrar?  Or that users will never be expected to want them?

**Comment by leviadam** [comment]
On the globalConstraintsRegistrar, we can add to it a feature to replace itself.
Although an upgrade can do that as well.

**Comment by dkent600** [comment]
OK, in any case, I think SchemeRegistrar should not be assigning the wrong permissions if given an address for UpgradeScheme  or GlobalConstraintRegistrar.

This really begs the question for me as to why we have this functionality (proposeScheme) at all if it is so limited.

**Comment by dkent600** [comment]
By design
