### ISSUE TITLE
Avatar is paying itself when scheme is registered with an organization

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#135]
The avatar is paying itself when scheme is registered.

For example, in organization.js, see:

`await scheme.registerOrganization(org.avatar.address)`

See also `SchemeRegistrar.proposeScheme`.

Maybe this op-op actually has desirable side-effects.  If so it could be good to add a comment in the code to that effect.  Otherwise this looks like a coding mistake.  Should the payer in fact be the current user, not the avatar?

**Comment by leviadam** [comment]
Not sure why you are saying the avater is paying itself.

**Comment by dkent600** [comment]
The `scheme.registerOrganization(org.avatar.address)` turns into `nativeToken.transferFrom(_avatar, beneficiary, fee)` where the beneficiary is the avatar (see 2_deploy_DAOstack.js).

So from = `_avatar` and to = beneficiary = avatar.

**Comment by leviadam** [comment]
The beneficiary should be the scheme. We are paying for the scheme.

**Comment by dkent600** [comment]
> The beneficiary should be the scheme. We are paying for the scheme.

Does that mean we have to change the code in each scheme's `registerOrganization` function from this:

```
      nativeToken.transferFrom(_avatar, beneficiary, fee);
```

to this:

```
      nativeToken.transferFrom(_avatar, address(this), fee);
```

**Comment by leviadam** [comment]
Nope. The one who built the scheme sets who is the beneficiary.
So we are paying for the scheme. But the payments go to whomever the admin if the scheme decided.

**Comment by dkent600** [comment]
*We* are building the schemes and are setting the beneficiary to == the avatar, not the scheme.  I guess I'm still missing something.

**Comment by leviadam** [comment]
Yes. We are building the schemes, and when we want to use the we pay ourselves.
But this is just on this occasion, every other org will pay us for using the schemes.

**Comment by dkent600** [comment]
OK cool, so the conclusion is that this is by design.

**Comment by leviadam** [comment]
Cool

**Comment by dkent600** [comment]
OK, I think the correct response to this is that I misread the code.  The scheme beneficiary is the DAOstack organization, set at deployment.  The avatar that SchemeRegister is passing into `registerOrganization` is the organization that is doing the registering.

Sorry for the misdirection.
