### ISSUE TITLE
reduce the number of transactions when creating an organization

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#136]
When creating an org with 4 schemes, `Organization.new` is generating 15 transactions.  More around four are expected.  We need to understand what is going on.

**Comment by dkent600** [comment]
Here is where the transactions are occurring in the Arc javascript code.  With three schemes there are 12 transaction, as follows.  Line numbers are in organization.js:

Count|Line #|Code
-----|------|----
1|354|genesisScheme.forgeOrg
2|377|org.votingMachine.setParameters
3,4,5|400|scheme.setParams
6|430|genesisScheme.setInitialSchemes
7,9,11|443|token.transfer
8,10,12|444|scheme.registerOrganization

**Comment by dkent600** [comment]
@leviadam

**Comment by leviadam** [comment]
We can avoid at least 5 here I think.
The transfer we can do all 3 at once.
The register organization we can set the flag to the controller to do automatically.

**Comment by dkent600** [comment]
Regarding the transfer:  In 2_deploy_DAOstack.js we do have a constant value for the amount of the scheme fee.  You're OK with assuming that will always be the case?  Thus the transfer reduces to one call where the amount is the UniversalRegisterFee * the number of schemes being registered. 

Regarding the autoregister flag:  Could be I'm not understanding the proposal here.  I see such a flag used in SchemeRegistrar when proposing a new scheme, but it still results in a Transfer.  In any case, we are not proposing here, we are in effect executing.   Finally, `scheme.registerOrganization` is not a controller operation, it is a scheme operation.  If we're not going to pay a fee to register the organization, then we got to add or modify code in the scheme to make that possible.

**Comment by orenyodfat** [comment]
pr #208 Reduced the number of txs needed for UniversalSchemes. 
For none universal scheme the picture is slight brighter ...might not need to register organization and pay fee (but not granted).

**Comment by orenyodfat** [comment]
pr #231  reduce the needs for token transfer txs for universal schemes.
So now for 3 schemes there is a need for 6 txs.
@dkent600 can we close this issue ?

Count|Line #|Code
-----|------|----
1|77|genesisScheme.forgeOrg
2|101|org.votingMachine.setParameters
3,4,5|117|scheme.setParams
6|132|genesisScheme.setSchemes

**Comment by dkent600** [comment]
@leviadam I have not closed this because I have not yet had the ability to test it and report on the results.  As a matter of due diligence, I want to see it the results in the Alchemy demo running against Kovan.

**Comment by dkent600** [comment]
I'm now seeing 6 transactions.  I need to confirm whether any of those are being needlessly caused by the Alchemy demo.

**Comment by orenyodfat** [comment]
>  I want to see it the results in the Alchemy demo running against Kovan. 

What is the logic behind that ? What wrong with ganache for testing number of txs ?

**Comment by orenyodfat** [comment]
@dkent600 
I think this issue  (if there is an issue ) not belong to this repo any more.
There is defined number of txs to forge an org which is derived from arc architecture and apis.

**Comment by dkent600** [comment]
> What wrong with ganache for testing number of txs 

Indeed, I probably could count the txs in the ganache log output.

At any rate, if you're OK with 6, then this can be closed.
