### ISSUE TITLE
Feature: Provide a service that returns archive of Arc contracts

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#138]
Could be great if we could provide a service that provides information about all of the contracts that have been made available by Arc in the entire history of Arc.

This information would include:

1) the key (like "SchemeRegistrar")
2) the address
3) the Arc version in which the contract was first published, or else a contract-specific version
4) friendly name?
5) the contract json file?

This should be done in a way that enables applications like Alchemy to:
1) identify whether a given address comes from Arc (because some won't have done)
2) enumerate all of the:
   * schemes, optionally filtered by scheme key
   * voting machines
   * global constraint types

   that have ever come from Arc, thus making them available for selection in an application's user interface.

**Comment by dkent600** [comment]
I think this probably needs to be a web service.  Hosting could be a straight web server or perhaps something like IPFS.

**Comment by dkent600** [comment]
https://github.com/daostack/daostack/issues/142#issuecomment-347270739

**Comment by tibetsprague** [comment]
Draft spec here, ready for comments https://docs.google.com/document/d/1aBrH9N57CDg3L7b_F8DDM0ZBks63qQkXkIfGvvBTu6U/edit?usp=sharing

**Comment by leviadam** [comment]
This belongs in the new repo.
