### ISSUE TITLE
Feature: Provide a means of providing contract information about an address

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#139]
Enable applications to determine the type of scheme represented by an arbitrary address.

Create a new Arc javascript method that takes an address and returns:

`Null` if:
1) the address is not an Arc scheme, or 
2) the resolved Arc scheme is not compatible with the current Arc scheme of the same type.

Else:

1) the "type" (for example, "SchemeRegistrar"
2) the friendly name "for example, "Scheme Registrar"

A truffle contract need not be returned because we are assuming compatibility between the current Arc scheme and the one being identified (*is it correct to assume that the current truffle contract will work OK in this instance?*).  In other words, I should be able to use `currentContract.at(theAddress)` where `theAddress` is for an older or newer scheme than has the same interface as the current one.

**Comment by dkent600** [comment]
@tibetsprague  just a heads up on:  "the resolved Arc scheme is not compatible with the current Arc scheme of the same type."  I can implement most of this feature request myself, but figure I'll leave this detail to you, or perhaps to when/if someone works #138.

**Comment by dkent600** [comment]
Ideally, in the case that a contract is newer than the library then it would be great if each contract had a method that would return the type of contract it is (same value as we will have in the json). Thus we would at able to know whether an arbitrary address not found in the json is in fact an Arc scheme, and what type it is.  The contract could also return its friendly name.

**Comment by leviadam** [comment]
I think this issue should be moved to the js  repository.
