### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#14]
# Roadmap

## Step 1: Basic solidity infrastructure

At this point we have a generic upgradeable DAO with reputation, majority voting, and the possibility to mint and sell tokens, distribute reputation.

#11 #19 #5 #25 #29

## Step 2: Basic UI

See #15 for details.

## Next features 

 * Sale of tokens for other tokens (not ETH) with fixed rate 
 * Varying sale schemes (possibly with vesting) (template for the general token distribution scheme)
 * Possibly (decaying) reputation distribution scheme to token buyers
* Vested tokens scheme for contributors (template for the general token distribution scheme)
 * Possibly let successful contributor to choose from vested-amount range option
* Reducing reputation by supermajority vote (80%?) (right now reducing and increasing is symmetric)
* Internal successful vote translated to external vote
* Conditions to trigger external contribution
* Affiliate contract (my own address for buyers / contributors) to give reputation + tokens for deployer
* Reputation flow upon vote according to alignment

**Comment by leviadam** [comment]
No longer relevant.

**Comment by Alonski** [comment]
Is it still relevant to link to this from the roadmap?
https://github.com/daostack/daostack/blob/master/docs/roadmap.md#smart-contracts
