### ISSUE TITLE
Bug: UpgradingScheme removes itself when its own address is passed as new UpgradingScheme

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#140]
UpgradingScheme removes itself when its own address is passed as the new UpgradingScheme in `proposeChangeUpgradingScheme`.

The result is that the user ends up with a corrupt DAO.

To handle this case `proposeChangeUpgradingScheme` should revert.

**Comment by leviadam** [comment]
Great work. Fixed.

**Comment by dkent600** [comment]
I am still ending up with a corrupt DAO in this scenario.

**Comment by leviadam** [comment]
How come? I updated the code so that it will not remove itself.

**Comment by dkent600** [comment]
In `organization.at`, the following line:

`var reputationAddress = await org.controller.nativeReputation();`

throws the following exception:

"Error: VM Exception while executing eth_call: invalid opcode"

**Comment by leviadam** [comment]
This is very weird, reputation have nothing to do with it.
Are you sure you just tried to change the upgrading scheme?
Maybe you actually performed an upgrade and replaced the controller?

**Comment by dkent600** [comment]
I'm definitely not changing the controller.  I confirmed that the crash is happening in `nativeReputation`

**Comment by leviadam** [comment]
Found it. It was a bug in the backend! Good job!
Fixed it.

**Comment by dkent600** [comment]
Now I find that in this case `proposeChangeUpgradingScheme` is throwing an exception, "revert"

**Comment by leviadam** [comment]
This was a permission issue, solved it.

**Comment by dkent600** [comment]
If this is fixed we should add a test for it:

```
it("proposeUpgradingScheme javascript wrapper should modify the modifying scheme", async function() {

    const organization = await forgeOrganization();

    let upgradeScheme = await organization.scheme('UpgradeScheme');

    assert.isTrue(await organization.controller.isSchemeRegistered(upgradeScheme.address), "upgrade scheme is not registered into the controller");

    let tx = await upgradeScheme.proposeUpgradingScheme({
      avatar: organization.avatar.address,
      scheme: upgradeScheme.address,
      schemeParametersHash: SOME_HASH
    });

    // newUpgradeScheme.registerOrganization(organization.avatar.address);

    const proposalId = getValueFromLogs(tx, '_proposalId');

    organization.vote(proposalId, 1, {from: accounts[2]});

    assert.isTrue(await organization.controller.isSchemeRegistered(upgradeScheme.address), "upgrade scheme is no longer registered into the controller");

    assert.equal(await organization.controller.getSchemeParameters(upgradeScheme.address), SOME_HASH, "parameters were not updated");
  });
```

**Comment by leviadam** [comment]
Cool. Why don't you add it and PR?

**Comment by dkent600** [comment]
Sure, I wanted to be able to associate a PR with an issue..
