### ISSUE TITLE
UpgradingScheme.proposeChangeUpgradingScheme does not call the new scheme's registerOrganization

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#141]
When a new scheme is added via SchemeRegister, we see:

```
      if (proposal.autoRegister) {
        UniversalScheme(proposal.scheme).registerOrganization(Avatar(_avatar));
      }
```

This is not present when replacing the UpgradingScheme using `UpgradingScheme.proposeChangeUpgradingScheme`.

Seems like it should be.

**Comment by leviadam** [comment]
There is no autoRegister flag at the moment there. 
It can be kept in the backlog. Don't think it is important at the moment.

**Comment by dkent600** [comment]
OK, as long as this doesn't result in a corrupt DAO (I haven't been able to test this case yet).

**Comment by leviadam** [comment]
OK, closing for now.
