### ISSUE TITLE
SchemeRegistrar should unregister an existing scheme before adding a new scheme

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#142]
SchemeRegistrar should unregister an existing scheme before adding a new scheme.  Otherwise we can end up with multiple schemes of the same type registered with an organization.

**Comment by leviadam** [comment]
I do not think so, we can have two schemes of the same type.

**Comment by dkent600** [comment]
OK, but that is not what you said recently in slack:

> dragonfly [3:57 PM] 
> would I be correct in assuming that it _should_ not be possible to register, with an organization, a given type of scheme at multiple addresses?  (for example, "UpgradingScheme" at two or more addresses)?
> 
> leviadam [5:00 PM] 
> Yes

**Comment by dkent600** [comment]
It will be tough for the users to distinguish between schemes of the same type.  We should perhaps enable schemes to have versions.  (see #138 and #139)

**Comment by leviadam** [comment]
There is a confusion here.
A scheme has a specific address. But the same code can be deployed several times. We will not prevent the registration of the same code from different addresses.

**Comment by leviadam** [comment]
I think we should have versions.

**Comment by dkent600** [comment]
If I understand, assuming schemes have version numbers:

OK: registration of multiple schemes of the same type having the same version
Not OK: registration of multiple schemes of the same type having different versions

What is the use case in allowing this?

**Comment by leviadam** [comment]
Not sure how you got this conclusion.
The backend will allow any address to be registered.
You cannot register the same address twice (actually, you can, but it changes nothing).

**Comment by dkent600** [comment]
Right now one can register, for example, two GlobalSchemeRegistars, each at a different address.  They may have the same code, and they may not.

I believe you are saying that is OK, with no restrictions.

Alchemy will need some adjustments to handle that case.  *I would like to understand what is the use case for this so I can best understand how to handle it in Alchemy.*

As we have noted,  users will want to have a scheme version so they can distinguish between multiple schemes.  Also so they can tell whether a scheme is compatible with the version of Arc they are using.

However, a version number will not help if the user has registered two schemes having the same version.  In this case the only sure way to distinguish between the two will be their address, which is not very informative nor easy to use.     I suppose we can ask the applications to handle how they want to handle this case, probably by preventing it from happening.  Again, this will require a version number, or perhaps comparison of the hash of the contract code (I'm sure offhand whether truffle provides that).

If all of the above is correct, then I would just request a description of the use case(s) involved, and then we could close this issue, deferring to #138 and #139.

**Comment by leviadam** [comment]
But what difference does it make? We decide which schemes alchemy known or not. We do so not based on the code, but based on the address. If there is an address you do not recognize, you just say there is an unrecognized scheme.

**Comment by dkent600** [comment]
This has nothing to do with non-Arc schemes.  Further, I don't want to say "unrecognized" for legitimate Arc schemes that are older or newer that the Arc library I'm using.  I want to be able to use those schemes, _as long as they are compatible with the Arc library I'm using_ (hence #138 and #139).

The cases I am concerned about are:

Registering two schemes of the same _Arc_ type (let's say SimpleContributionScheme).  By design they have different addresses.

Case 1:  the code is identical
Case 2:  the code is different

In Case 1 the user is not able to distinguish between the two schemes, other than by address.  I don't see any reason for this case to ever happen and am wondering if there is any reason for allowing it, either in the application or the library.

In Case 2 the user could distinguish between the two given a version #.  But in order to do this well in the application, I would like to understand _why_ anyone would want do this, and for us to be clear that there is some compelling reason to allow this flexibility and force the resulting complexity in the UI.

**Comment by leviadam** [comment]
Case 1 will never happen. As we will not put two addresses with the same code in Arc.js.
Case 2 is legit, we need versioning for that.

**Comment by dkent600** [comment]
Technically Case 1 *can* happen.  As you said above, we may deploy the same code more than once (ie, to two different addresses).  If it is never going to happen, then either the application or the library will need to prevent it.

**Comment by leviadam** [comment]
Arc.js has a list of schemes that we have to maintain. We will not list the same scheme twice on two different addresses.

**Comment by dkent600** [comment]
We will just have to be careful that once we deploy a scheme for the first time, and assign it a version, that even if we deploy that same scheme version again, we will continue to refer in that arc scheme list only to the originally-deployed scheme.   The newer ones will effectively forever be orphans, never to be used only because no-one will ever know about them.

**Comment by tibetsprague** [comment]
this is all basically what I am supposed to be working on. how we track the deployed addresses and distribute to people who want to use daostack and arc. it is now seeming to me that we are going to need humans to manage this process, that there is no automated way to track the deployed addresses and make sure that they refer to the valid, working contracts that they are supposed to. do you guys agree?

**Comment by dkent600** [comment]
Well, I'm no an expert in this space  (not yet  ;-) ), but it does seem as though it could take a lot of work to develop such an automated tool.

Each scheme needs its own independently-tracked version, to be incremented only when the contract code has actually changed.  Seems like we would follow the same versioning rules that we agreed upon for Arc itself.

As I see it, the entire version history would be stored separately from the Arc library, and be remotely accessible to applications (per #138).

**Comment by leviadam** [comment]
I agree this should be manual at the beginning.
@tibetsprague
