### ISSUE TITLE
SchemeRegistrar is unable to remove UpgradeScheme and GlobalConstraintRegistrar 

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#144]
`SchemeRegistrar.proposeToRemoveScheme` is unable to remove UpgradeScheme and GlobalConstraintRegistrar .  It triggers "invalid opcode".

I suspect this is related to #129.

**Comment by leviadam** [comment]
It is not a bug.
It just doesn't have the permissions.
One can give it the permissions to do so, but I feel this is a better configuration.

**Comment by dkent600** [comment]
It seems weird to me that SchemeRegistrar would be so limited.  I'm interested in how this is a better configuration?

**Comment by leviadam** [comment]
It is not limited at all. It can add and remove any scheme that does not require the upgrading permission or the global constraint permission. This is good security.

**Comment by leviadam** [comment]
We are starting with a small set of schemes, so it looks like it is very limited, but it is not.

**Comment by dkent600** [comment]
OK, applications will need to have a generic way to anticipate which schemes SchemeRegistrar will be allow to work with.  At this point I guess they can filter out any schemes that don't have permissions 1 or 3.

**Comment by leviadam** [comment]
In general any scheme in the js file should know which permissions to ask for.
The library should check that the registering scheme has enough permissions to register such a scheme.

**Comment by dkent600** [comment]
> In general any scheme in the js file should know which permissions to ask for.

They do.

> The library should check that the registering scheme has enough permissions to register such a scheme.

We can do that, but applications will likely also want to do it (Alchemy is one that does).  Either way it requires understanding of how SchemeRegistrar is restricted by its own permissions and those the permissions of the schemes it is asked to add or remove.  I'm not very comfortable with requiring knowledge of, and creating dependencies on, what seems like a low-level understanding about how these schemes relate.

I don't have a great alternative at the moment other than adding a function to SchemeRegistrar like `pluggableSchemes` or something like that that returns a list of scheme keys (keys like "SimpleContributionScheme") that it is able to work with.  This would nicely hide the implications of permissions.

**Comment by leviadam** [comment]
Why is this low level? you can read the permissions and give access to it.

**Comment by dkent600** [comment]
"give access to it" is not clear to me.  Can you please describe what you meant by that, thanks?  I want to make sure there is not something I'm unaware of.

The question is whether there is any advantage to requiring that the user know *why* any given scheme can or cannot be the object of SchemeRegistrar operations.

Hiding (while documenting) the reasons enables us to change the underlying logic without requiring the user to make code changes.  Hiding enables the user to work with the restrictions on SchemeRegistrar without having code dependencies on the underlying logic behind the restrictions.

It is a judgment call that takes into account the likelihood of changes, the difficulty of coding the logic, and so on.  I'm not really arguing strongly one way or the other on this one.  We may decide that this logic will never change, or if it does, that we are willing for it to be a breaking change.  We may decide to require that users have a full understanding of all the implications of contract permissions and code directly to them.  We might find that in this case hiding the implications of permissions is not worth the effort.

**Comment by leviadam** [comment]
I think a developer using the JS library should know there are permissions. Should know which permissions a scheme requires, and should know which permissions each scheme actually have.

**Comment by dkent600** [comment]
Can close, is by design.
