### ISSUE TITLE
Bug: SchemeRegistrar.proposeScheme throws invalid opcode on non-arc scheme

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#145]
Trying to register a non-arc scheme as follows results in an "invalid opcode" exception.  Is this not the correct way to do this?

```
this.contract.proposeScheme(
        options.avatar, <== valid address
        options.scheme, <== any non-null address
        options.schemeParametersHash,  <== Alchemy is passing NULL_HASH
        false,  <== assume not a registering scheme (how can we know?)
        NULL_ADDRESS,  <== do we make assumptions about the native token?
        0,  <== do we make assumptions about the fee?
        true <== auto register 
 );
```

**Comment by dkent600** [comment]
Hmmm, I'm thinking that the app may have to pass in a token address and fee....will verify whether this works....

**Comment by leviadam** [comment]
I don't see why it must be a valid token address.

**Comment by dkent600** [comment]
I find that whether I'm able to register a non-arc scheme depends on the scheme address that I tell it to register.  Since I don't have a true non-arc scheme to add, I'm sending fake addresses, assuming it wouldn't matter what address I send, but apparently it does.

When I send the address of the avatar or the SimpleContributionScheme or SchemeRegistrar, it succeeds.

When I send the address of the controller, token, UpgradeScheme, or GlobalConstraintRegistrar, or any other random address, it fails.

**Comment by dkent600** [comment]
I think I get why sending the schemes addresses would succeed or fail (permissions).  Except that I don't get why sending a non-scheme address fails (their permissions would be zero, but why would that be a problem?), and I don't get why sending the Avatar address would succeed (it should also have permissions of zero).

**Comment by orenyodfat** [comment]
@dkent600 is that not duplicated at #181 ?

**Comment by dkent600** [comment]
Indeed, let's close this one.
