### ISSUE TITLE
Controller.unregisterSelf doesn't fire UnregisterScheme event

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#146]
`Controller.unregisterSelf` doesn't fire `UnregisterScheme` event.  It should, otherwise applications will not be apprised that the scheme has been unregistered.

This is relevant to `UpgradeScheme.execute` after `proposeChangeUpgradingScheme`

**Comment by leviadam** [comment]
Very good. This is a bug.
Fixing it now.
