### ISSUE TITLE
Way to add/modify/remove schemes regardless of permissions

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#148]
It looks to me like it is possible to use UpgradeScheme replace the controller with one that would allow `SchemeRegistrar` to replace itself with another (non-Arc) `SchemeRegistrar` that is able to add/modify/remove `GlobalConstraintScheme` and `UpgradeScheme` schemes (something that the default `SchemeRegister` doesn't know how to do even if it were allowed to).

Is this a hole or a feature?

**Comment by leviadam** [comment]
It is a feature. 
Upgrading the controller is the most brutal thing. 
We do not claim anything about what will be afterwards.
