### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#15]
The UI should make interacting with a DCO simple and intuitive. In the spirit of the DAO stack, we implement functionality in an incremental way.

* Token  (see your balance, transfer tokens)
* MintableToken  (create new tokens (owner only))
* Reputation  (see your rep, perhaps see also info about distribution of rep)
* generic Ballot (vote on an issue. see the proposals, vote for on, see the current voting situation, etc)
* Backfeed style DCO (...)

**Comment by leviadam** [comment]
Out of date. Already exist in the demo.
