### ISSUE TITLE
Bug: organization.schemes does not reflect current state of scheme registration

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#151]
`organization.schemes` has a couple of problems:

1) when a given scheme has been modified then `organization.schemes` returns two identical records of the modified scheme.  Three modifications then three records, and so on.

The fix could be that `SchemeRegistrar` fire different events when modifying versus when adding a scheme. Barring that, `organization.schemes` will need to check for dups.

2)  when a given scheme has been unregistered, then `organization.schemes` still returns a record for the removed scheme.

`organization.schemes` should be checking UnregisterScheme events.

Note:  I have code in Alchemy that already does all of this correctly.

**Comment by leviadam** [comment]
I think this better be handled off chain.

**Comment by dkent600** [comment]
k, i'll copy or move my code from Aurelia into organizations.

**Comment by dkent600** [comment]
Some code was merged to address this.  There are an improvement, but not 100% sufficient.  Final changes to come in a separate PR.

**Comment by dkent600** [comment]
The code for this has been moved over to the arc-js repo.  So this daostack issue can be closed.
