### ISSUE TITLE
Feature: Add autoregister to UpgradeScheme.proposeChangeUpgradingScheme

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#154]
Feature: Add autoregister to `UpgradeScheme.proposeChangeUpgradingScheme`, just like we already have for `SchemeRegistrar.proposeScheme`.

**Comment by dkent600** [comment]
Be sure to also add this to the javascript wrapper function `proposeUpgradingScheme`, where you will find part of what you need already there, just commented-out.

**Comment by leviadam** [comment]
I think it is a nice feature.

**Comment by dkent600** [comment]
Add to backlog
