### ISSUE TITLE
Feature: Implement an ability to replace GlobalConstraintRegistrar

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#155]
Per #129, we lack a way to replace GlobalConstraintRegistrar in a DAO.

**Comment by leviadam** [comment]
Good. you can put it in the backlog on the project tab.

**Comment by dkent600** [comment]
OK, i'm not sure I did what you requested wrt the backlog, let me know if not.

**Comment by leviadam** [comment]
You did good.
