### ISSUE TITLE
Important operations should be logged (as events)

### ISSUE THREAD

**Issue by yaronvel** [daostack/daostack#16]
Even though ethereum blockchain is public and technically any data is extractable by anyone, it is still technically cumbersome to reason on operations that are not explicitly logged.
Logging important operations, such as votes, token minting, reputation creation etc, as solidity events generates public trace and thus both increase the credability of the contract (e.g., one can witness that the contract is running as expected) and give the user an interface to programmingly react to important operations (e.g., if person X votes Y, then I will also vote Y).

**Comment by jellegerbrandy** [comment]
+1

**Comment by yaronvel** [comment]
Guidliness/conventions for logging might be a good start.
