### ISSUE TITLE
New working methodology

### ISSUE THREAD

**Issue by leviadam** [daostack/daostack#164]
Hi all,

After looking at several projects, and a bit of a mess we had in the repo I have decided it will be better to have a separate repo for the js library.
I think we will do the following. Every week we will merge dev-->master, and build an npm package with the contracts.
We will never deploy real contracts from this repo.

The library repo will handle the whole mass of deploying and managing the different deployments.
@tibetsprague @orenyodfat @dkent600 

In the meantime you might want to use the dev branch as submodule, until we get it working.

**Comment by dkent600** [comment]
What is the need to do an every-week merge from dev to master?

**Comment by leviadam** [comment]
To give you access to the latest code.

**Comment by dkent600** [comment]
Which repo are you referring to?

**Comment by dkent600** [comment]
@leviadam You named the new repo "arc.js".   I'm not real wild about repo names with a '.' in them, nor about the ".js" that is saying something about javascript that I'm not sure is or will always be true.

In any case, we already have the name "daostack-arc".  Is that the name we wish to retain for the contracts repo/product/package?  If so then there is a lack of consistency in naming/branding.

Does "Arc" refer to the contracts, or to the library?

**Comment by leviadam** [comment]
I will change it to "arc-js" for now.
Naming will be decided on the coming week.
