### ISSUE TITLE
TypeError: Member "increaseApproval" not found or not visible after argument-dependent lookup in contract StandardToken

### ISSUE THREAD

**Issue by tibetsprague** [daostack/daostack#172]
@orenyodfat commit 307b20d934f375b1968f2765027b0ccc64f42619 broke compilation. You are calling token.increaseApproval which doesn't exist on StandardToken

**Comment by orenyodfat** [comment]
increaseApproval exist in zeppelin-soidity : 
which zeppelin version you are using ?
https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/StandardToken.sol#L70

**Comment by tibetsprague** [comment]
1.4.0, the version thats in our package.json

**Comment by tibetsprague** [comment]
Ugh, I just had to remove everything in installed_contracts/ and now it works :(
