### ISSUE TITLE
Deploying GenesisScheme throws Error: Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by tibetsprague** [daostack/daostack#173]
The error occurs on this line:       
`reputationAddress = await ControllerInst.nativeReputation();
`

**Comment by leviadam** [comment]
Which branch are you working on?

**Comment by tibetsprague** [comment]
Dev

Sent by m

**Comment by leviadam** [comment]
Can you try doing 'yarn' anf also clear the build folder?

**Comment by tibetsprague** [comment]
yarn didn't help, but removing everything in installed_contracts/ did
