### ISSUE TITLE
Bug: invalid opcode when adding non-arc scheme to an org

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#181]
I am getting an invalid opcode when adding a non-arc scheme to an organization (`SchemeRegistrar.proposeScheme`).

Parameter | Value
------------ | -------------
AutoRegister | true
IsRegisteringScheme | false
Fee | 0
Scheme address | 0x1000000000000000000000000000000000000000
Scheme Parameters Hash | 0x1000000000000000000000000000000000000000000000000000000000000000
Token Address | the native token of the Dao

**Comment by orenyodfat** [comment]
thanks @dkent600
This happened only with AutoRegister == true .right ?
It looks like it come from this [point](https://github.com/daostack/daostack/blob/dev/contracts/universalSchemes/SchemeRegistrar.sol#L248) where the contract trying to call non existing function on a contract(address) without a fallback function.
I guess SchemeRegister should not allow AutoRegister for non-arc (UniversalScheme type) scheme and should revert on the proposal phase if someone trying to propose that.

**Comment by dkent600** [comment]
> This happened only with AutoRegister == true .right ?

Indeed it works fine when autoRegister is set to false.

So for ds-arc-js I propose to do the following, to set autoRegister:

       * Default to false for Arc schemes (can be overridden to true)
       * For non-Arc schemes, ignored and always set to false

**Comment by dkent600** [comment]
@orenyodfat Having proposed the above behavior, I must say I'm not confident about it; namely, should the default be true or false?  Should it even be an option for the user?  Is there ever a use case where someone would want to set autoRegister to false on a true DAO scheme?  What would that case be?

Thanks.

**Comment by orenyodfat** [comment]
@dkent600 AutoRegister is currently referring to register an organization (the one which is sent along with the proposal) to a UniversalScheme. 
how about a case where one would like to register a new scheme to the organization but would like to register other organization to this scheme.
in the current implementation it can do that by setting AutoRegister==FALSE and if the proposal approved it can call registerOrganization for the desire organization.
- registration of organization might cost some fee that one would like to avoid if not necessary . 

By the way, how you differentiate between non-arc and arc schemes in the ui ?is that a user setting ?

**Comment by orenyodfat** [comment]
I guess we need to change naming :  AutoRegister should be AutoRegisterOrganization .
It is confusing.

**Comment by dkent600** [comment]
Thanks @orenyodfat, do you have an opinion, then, about which would best be the default value for autoRegister, true or false, for DAO schemes?  False would minimize the chance of accidentally registering the wrong organization into the scheme, but leave open the possibility of *not* registering the DAO in what might be the most common case.  True would simplify the API in what might be the most common case.

> By the way, how you differentiate between non-arc and arc schemes in the ui? is that a user setting ?

See the attached screenshot.

![image](https://user-images.githubusercontent.com/1821666/34273842-0cf42b72-e664-11e7-8682-0e1357cd95b5.png)

**Comment by dkent600** [comment]
@orenyodfat There is one aspect of the scenario you painting that I wonder about. Understanding that when we execute a proposal to add a scheme, we register the scheme parameters with the controller of the SchemeRegistrar that is executing the proposal.

If autoRegister is false, and the user later registers _a different_ organization into the scheme.  What if that different organization also has a different controller?

**Comment by leviadam** [comment]
AutoRegister is only a helper to reduce the number of TXs.
It can be used only when it is a scheme that the library knows about.

**Comment by dkent600** [comment]
Unless there is a valid scenario where a user would want to set autoRegister to false for a known Arc scheme, I am inclined to not expose it in the arc-js API.

**Comment by leviadam** [comment]
This is ok with me.

**Comment by orenyodfat** [comment]
👍 @dkent600 i guess this issue can be closed .

**Comment by dkent600** [comment]
Done, autoRegister will be hard-coded in arc-js, no option for the user to override.
