### ISSUE TITLE
Fees paid when submitting a contribution are computed incorrectly

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#186]
Just via code inspection of SimpleContributionScheme.sol, this looks wrong:

```
        if (controllerParams.schemeNativeTokenFee > 0) {
            _avatar.nativeToken().transferFrom(msg.sender, _avatar, controllerParams.orgNativeTokenFee);
        }
        if (controllerParams.schemeNativeTokenFee > 0) {
            nativeToken.transferFrom(msg.sender, _avatar, controllerParams.schemeNativeTokenFee);
        }
```

I'm not going to suggest what it should be because comments elsewhere in the .sol file are not entirely clear or consistent as to how these two parameters are to be used.

Please also document them here so we can also document them correctly in ds-arc-js, thanks.

**Comment by orenyodfat** [comment]
👍
