### ISSUE TITLE
SimpleContributionScheme.sol - _contributionDescription to be bytes32  

### ISSUE THREAD

**Issue by orenyodfat** [daostack/daostack#188]
The proposal is to make _contributionDescription bytes32 instead of string.

- This will limit the description to 32 bytes and make the JS side work a bit harder though it will be cheaper in terms of gas and will eliminate the deep stack issue at submitContribution function.

http://solidity.readthedocs.io/en/develop/types.html?highlight=string#dynamically-sized-byte-array

If 32 bytes is not enough for the contribution description so it is another story.

**Comment by dkent600** [comment]
32 bytes would be 16 Unicode characters.  In general it is hard to imagine that 16 bytes will be enough to describe a proposal.

We could apply compression which would indeed be some extra work, but with short strings it may not gain much (in fact could lose).

Could another option be to store the information as either bytes32 or string depending on the length of the passed-in string, being sure to retrieve the correct one when requested?

**Comment by leviadam** [comment]
It can be 32 bytes and if it is longer to store just the hash.
The non-hashed data should be stored on IPFS or something similar.

**Comment by dkent600** [comment]
From an applications perspective, I prefer having the option to pay for storage of the entire description.  The alternative cost of additional coding and hosting against IPFS or some other hosted DB could be far greater.

I wonder if the proposal fee could be used to pay for storing the description?  Does that make any sense?

**Comment by orenyodfat** [comment]
@dkent600 I guess that we want to keep our contracts cheap as we can and store the minimum needed.
Having a provable decentralized storage (e.g IPFS , SWARM) enable us to store data off-chain much cheaper than on the blockchain.
@leviadam I see that _contributionDescription already stored  as hashed  on the contract https://github.com/daostack/daostack/blob/dev/contracts/universalSchemes/SimpleContributionScheme.sol#L167 
I guess that the contract need to get it already hashed.

**Comment by leviadam** [comment]
That was the original intention.

**Comment by orenyodfat** [comment]
👍

**Comment by dkent600** [comment]
Is it Arc that is proposed to use IPFS, Arc-Js, or the application?

**Comment by leviadam** [comment]
Definitely not arc, could be arc-js.

**Comment by dkent600** [comment]
@orenyodfat  @leviadam  

Such an extra storage system could also be used to store stuff like Dao avatar images.

We may want to publish that functionality as a separate package.  Thinking about it....

**Comment by orenyodfat** [comment]
Yes..lets open a new issue for that..
Will close this one.

**Comment by dkent600** [comment]
I did open one -- in the arc-js repo.  :-)
