### ISSUE TITLE
Combine RegisterScheme and UnregisterScheme scheme events

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#189]
Having separate `Controller.RegisterScheme` and `Controller.UnregisterScheme` scheme events is a pain.  One has to watch them separately, with the associated double impact of constant pinging of the network, and when trying to obtain a history, one has to compute the relative timing of register versus unregister to know which ones come first.

Would it be possible to combine these two events into a single one that provides an argument indicating whether it is to register or unregister?

**Comment by leviadam** [comment]
Hi @dkent600,

I'm not sure about this.
To understand how I think this should be done I'll give an example. 
In a token contract, you can either integrate all the transfer logs to recover the balances, but this is not how it is done. You only use the events to see which addresses were ever used and then just check balance for each of these addresses.
Similarly, for every scheme that was ever registered you can just check if it is registered, you don't have to integrate the events.

**Comment by dkent600** [comment]
Thanks @leviadam ,

This is still more complicated, and involving more hits on the chain, than simply having a single event as I proposed, and it still has the cost of having to poll for two events instead of one while monitoring for new events in real time (that means two http requests going out about once per one or two seconds and hitting the chain).

Is there any reason *not* to have a single event other than having to make the code change?  It seems much cleaner.

**Comment by leviadam** [comment]
No real reason. I think we might do that. Your opinion @orenyodfat ?
But I do not think it is as you said wrt the number of requests. The web3 allows you to listen to all events in a contract.

**Comment by dkent600** [comment]
> The web3 allows you to listen to all events in a contract.

Cool, I will look into that.

**Comment by leviadam** [comment]
https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-allevents

**Comment by orenyodfat** [comment]
well, trying to examine the related gas cost of this issue: 
Combine these to 2 one event with additional indexed param (register/unregister) will increase the gas cost needed as indexed parameters in events have additional gas cost.

**Comment by dkent600** [comment]
ok, i'll go with the suggested algorithm
