### ISSUE TITLE
Revert on contribution when contributing ethers

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#190]
Whenever I try to do a simple contribution that includes an amount of ethers, I get a revert.  Any other form of donation works OK.

This is on testrpc.  Haven't tried on Kovan.

**Comment by dkent600** [comment]
Doesn't seem to matter how small the contribution is

**Comment by orenyodfat** [comment]
@dkent600 could you please send a link to your test ?
Please make sure the org's avatar has enough balance before trying to contribute from.
Take a look here : https://github.com/daostack/daostack/blob/upgradescheme/test/simplecontribution.js#L226

**Comment by leviadam** [comment]
As @orenyodfat  said. I would guess the avatar does not have enough funds.

**Comment by dkent600** [comment]
@orenyodfat  Ah, I have been assuming that the _user_ was making the contribution.  In the real world, how does the avatar typically receive eth?

**Comment by leviadam** [comment]
No @dkent600 . The name is SimpleContribution (maybe we should change the name?) because it suppose to represent a contribution done by someone to the organization, and the organization is giving him eth/tokens as a reward. If there are no ethers to give, it will revert.

**Comment by orenyodfat** [comment]
@dkent600 @leviadam how about ContributionReward.sol ?

**Comment by leviadam** [comment]
OK with me. It can also be just SimpleReward.sol maybe.

**Comment by orenyodfat** [comment]
Not sure "Simple" is the best fits here. 
So there will be simple ,complex and very complex Rewards ? :)..
  
Albert Einstain : "Everything should be made as simple as possible, but not simpler."

**Comment by leviadam** [comment]
I leave it to you @orenyodfat . I'm not very good with naming.
