### ISSUE TITLE
Specs: should our standard token contract have a limit on the amount of tokens that can be created?

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#20]
In the current setup, the Token contract can mint unlimited new tokens. 

This may be unideal, because it makes all tokens infinitely dilutable, in principle. There is no garantee for a token holder that his tokens will continue to represent a certain guaranteed fraction of the total amount. Anyone who controls the mint function can dilute your tokens as much as he wants (assigning them to himself, for example).

Question: should we put a maximum limit on the amount of tokens that can be created, making them more similar to stocks in the real world?

**Comment by fmatan** [comment]
I don't think we should have a hard-coded limit within the global framework (that we've discussed internally and should describe in details somewhere else, beyond the code itself). 

We do need to have, though, a modular functionality of putting constraints into value-system contracts. Limited mining should be one such constraint, but could be many others.

The question of dilution is somewhat misleading as the network can debunk the value of the token anyway, simply but not adopting that token and moving to work with another token. At the end of the day, the value of the token is derived from the network effect, and the "investor" assumes the success of this network effect. He should also rely on the incentive for each individual to support the building that network effect, and if the latter is lacking then the entire model is not viable.

Protection of investor's tokens can be achieved in many ways. For example:

When you purchase a token you get it right away. However, when someone posts a successful contribution (which is voted to reward him) he gets "delayed tokens", say, he's rewarded with 100 tokens, in a delay of, say, 1 month.  The delay functionality can be (revocably) hard-coded in the distribution recipe (as discussed internally, see architecture); or, probably can also be hard-coded in the Master contract (and thus enforce it "forever"; again, up to the network moving to another tokens/value system). 

To code it in the Master contract perhaps we'd need to use another Escrow contract that keeps funds for certain amount of time.
