### ISSUE TITLE
change the method name `submitContribution` to `submitContributionReward`

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#204]
Change the method name `submitContribution` to `submitContributionReward`

**Comment by orenyodfat** [comment]
"submitRewardProposal" might describe better the function.

**Comment by dkent600** [comment]
Would "submitRewardProposal" be consistent with other function naming? Perhaps even better:  "proposeContributionReward"?  Still not consistent, but maybe the others should be renamed too.

**Comment by leviadam** [comment]
Both are ok with me.

**Comment by dkent600** [comment]
How about rewardContributionPropose?  ;-)

**Comment by leviadam** [comment]
:)
I think "proposeContributionReward" that was suggested is best. As it is more consistent.

**Comment by orenyodfat** [comment]
👍
