### ISSUE TITLE
After modifying SchemeRegistrar the SchemeRegistrar contract becomes unusable

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#206]
In testrpc, after modifying SchemeRegistrar the SchemeRegistrar contract becomes unusable -- both functions revert.

I see this in Alchemy on testrpc.

Related to:  https://github.com/daostack/Alchemy-Aurelia/issues/2

**Comment by orenyodfat** [comment]
Please send more informative steps to reproduce .

**Comment by dkent600** [comment]
OK, upon further investigation I find that this was a bug in arc-js.  To be fixed as part of https://github.com/daostack/arc-js/pull/2
