### ISSUE TITLE
GenesisScheme.setSchemes reverts in Organization.new

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#211]
`GenesisScheme.setSchemes` reverts in `Organization.new`

STEPS:
1. In helpers.Organization.new, change this:

    options.initialSchemes.addresses.unshift(org.tyrantAddress);
    options.initialSchemes.params.unshift(NULL_HASH);
    options.initialSchemes.permissions.unshift("0x0000000F");
    options.initialSchemes.fees.unshift(0);
    options.initialSchemes.feesTokenAddresses.unshift(NULL_ADDRESS);

to this:

    options.initialSchemes.addresses.unshift(org.tyrantAddress);
    options.initialSchemes.params.unshift(SOME_HASH);
    options.initialSchemes.permissions.unshift("0x0000000F");
    options.initialSchemes.fees.unshift(1);
    options.initialSchemes.feesTokenAddresses.unshift(tokenAddress);

2. run the genesisscheme tests.

RESULT:
The test "founders should get their share in reputation and tokens" will revert.

EXPECT:
Not to revert.

I suspect this is failing because the avatar does not yet have tokens to pay for universal scheme registration.

This is breaking Organization.new in arc-js because it requires the registration of SchemeRegistrar, UpgradeScheme and GlobalConstraintRegistrar.

**Comment by orenyodfat** [comment]
Thanks @dkent600 .
This helper code is not needed any more.
I will remove that.

**Comment by dkent600** [comment]
OK, @orenyodfat, but I would like to know if there is an issue here, represented by the fact the setSchemes is reverting.  It does the same for me in arc-js and is currently preventing arc-js tests from succeeding.

**Comment by orenyodfat** [comment]
I guess that it fail while trying to register to none universal scheme:
univsalScheme = 1(true) and org.tyrantAddress = web3.eth.accounts[5]; which is not universalScheme.

**Comment by dkent600** [comment]
Or else it is failing because of lack of funds for the avatar?  Or both?

**Comment by orenyodfat** [comment]
both.
Take a look here for universalScheme
https://github.com/daostack/daostack/blob/master/test/genesisscheme.js#L122
and here for none universalScheme :
https://github.com/daostack/daostack/blob/master/test/genesisscheme.js#L112

**Comment by dkent600** [comment]
yes, thanks, those are where I have seen the funding happening that wasn't happening in the code I reported on here, nor in organization.new:

`var standardTokenMock = await StandardTokenMock.new(avatar.address, 100);`
