### ISSUE TITLE
`yarn solium` problem on windows machines

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/daostack#215]
`yarn solium` lints incorrectly on windows.
![image](https://user-images.githubusercontent.com/33967618/34513696-29978914-f072-11e7-9c5a-769013ef9af8.png)

**Comment by orenyodfat** [comment]
@dev-matan-tsuberi not sure it is windows issue.
It might be related to your editor setup .
check your tab/space setting.

**Comment by dev-matan-tsuberi** [comment]
I actually tested this on a docker container running debian.

**Comment by orenyodfat** [comment]
so how it is related to windows ?

**Comment by dev-matan-tsuberi** [comment]
No idea what exactly the problem is. 
Seems to be an encoding issue according to @leviadam.
As I said, I ran it on debian without any issues. (generated only 5 warns)

**Comment by orenyodfat** [comment]
It might be known solium issue .
Take a look on this comment https://github.com/duaraghav8/Solium/blob/master/lib/cli.js#L172 .
It might worth to open an issue at solium and see what they say.
https://github.com/duaraghav8/Solium

**Comment by dev-matan-tsuberi** [comment]
opened issue on solium: https://github.com/duaraghav8/Solium/issues/162

**Comment by leviadam** [comment]
It is an encoding issue for sure. But it is on solium to solve it.
I do not see it as a problem as we are officially supporting only unix based development.
