### ISSUE TITLE
setScheme is reverting when scheme is obtained from .deployed()

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#226]
setScheme is reverting when the supplied scheme has been obtained using .deployed(), rather than .new.

While there is another issue, #225, where setScheme is reverting when the input token is not equal to the schemes' native token, this issue is different.

#225, however, gives an example of the code that is pertinent to this case:

> If I try to set a scheme creating like this, it works:
> 
> `schemeToAdd = await SchemeRegistrar.new(standardTokenMock.address, 10, accounts[0])`
> 
> (This is how it is done in the arc automated tests.)
> 
> However, if I try to set a scheme creating like this, it reverts:
> 
> `schemeToAdd = SchemeRegistrar.at((await SchemeRegistrar.deployed()).address))`
>
> (This is how it is done in arc-js.)

It is possible to overcome the issue described in #225 by passing the correct tokens into setScheme.  

Even then, setScheme still reverts when using .deployed() to supply the desired schemes.

It reverts on this line:

`UniversalScheme(scheme).registerOrganization(_avatar);`

as can be ascertained by deleting the line and seeing the test succeed.

The weird thing is, one can remove all the code in `UniversalScheme(scheme).registerOrganization` and setSchemes **still** reverts.

So to my eyes there is something wrong with this part: `UniversalScheme(scheme)`.

That's all I got.

**Comment by orenyodfat** [comment]
@dkent600 with which params you are deploying the scheme ?
Could you please write a simple test code which address the issue you are referring to ?

**Comment by dkent600** [comment]
Can't say for sure, but it is possible this is also happening in `SchemeRegistrar.proposeScheme`.

**Comment by orenyodfat** [comment]
Could you please write a small test to clarify your claims.

**Comment by dkent600** [comment]
@orenyodfat 

Extract the attached zip into the test folder.

Then run `truffle test .\test\genesisscheme.js`

[test.zip](https://github.com/daostack/daostack/files/1608872/test.zip)

**Comment by orenyodfat** [comment]
Thanks @dkent600 .
Please remember that you need first to transfer funds to the org avatar for the scheme registration with the same token that the scheme is using.
You are doing that ..but no to the scheme's token.
Please replace :  
> await org.token.transfer(avatarAddress, totalFees, { from: founders[0].address }); 

with : 

> var schemeRegistrarAddress = await SchemeRegistrar.at((await SchemeRegistrar.deployed()).address);
  const schemeTokenAddress = await schemeRegistrarAddress.nativeToken();
  var schemeToken = await StandardToken.at(schemeTokenAddress)
  await schemeToken.transfer(avatarAddress, totalFees, { from: founders[0].address });
