### ISSUE TITLE
Have stub file for solidity version

### ISSUE THREAD

**Issue by yaronvel** [daostack/daostack#23]
Create version.sol that would include only
`pragma solidity ^0.X.X;`

All our files (e.g., not zeplin's) should import it.

**Comment by jellegerbrandy** [comment]
why?

**Comment by yaronvel** [comment]
So when we upgrade to a new compiler we wouldn't have to change many files.
Just a thought.

**Comment by yaronvel** [comment]
Never mind. Tried to use it.
The compiler still issue a warning about missing pragma, even when the first line is to import `version.sol`.

**Comment by jellegerbrandy** [comment]
I assume the importer just skips the pragma - it is a statement about the file itself, not an instruction in solidity.
