### ISSUE TITLE
Problems running tests on windows .

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#241]
I am having a couple of problems running the tests in Arc.

1) `$npm_package_config_gasLimit` is not resolving to the number that it should.  This prevents migrations from proceeding in arc-js.
2) running `npm run test` produces the error message:  "Could not find ganache-cli", even though it is installed as a package in arc, and I have it also installed globally (though I don't think the scripts should be relying on the latter).

**Comment by dkent600** [comment]
Using this commit:  https://github.com/daostack/daostack/commit/58c04ea096cee43a89721db757ca35e83fb74d76

**Comment by orenyodfat** [comment]
This seems to be a windows issue  : 
For Windows users, environment variables follow a slightly different format, forgoing the $ and instead wrapping the var in %'s like so %npm_package_config_source% .
I will fix that soon.

**Comment by dkent600** [comment]
This could help:  https://www.npmjs.com/package/cross-conf-env

**Comment by orenyodfat** [comment]
yes..
Could you please handle that? as I do not have a window machine to test with currently.

**Comment by dkent600** [comment]
Sure, in the meantime, what about item #2?

**Comment by orenyodfat** [comment]
> Sure, in the meantime, what about item #2?

Seems like another windows issue.

**Comment by dkent600** [comment]
As far as I can tell, the ganache-cli problem is a bug in run-in-testrpc.  I created an issue on their site:  https://github.com/gnosis/run-with-testrpc/issues/6

**Comment by dkent600** [comment]
I really should have created these as separate issues, was lazy, sorry.

I have the fix for the problem with `npm_package_config_gasLimit` and will go ahead and PR it, since that will be sufficient to unblock arc-js.

The problem with ganache-cli only affects being able to run arc tests and does not immediately concern arc-js.

**Comment by dkent600** [comment]
I created #245 for the ganache-cli part of this.
