### ISSUE TITLE
2_deploy_organization.js no longer works for arc-js

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#242]
2_deploy_organization.js no longer works for arc-js

TokenCapGC is defined in 2_deploy_organization.js , but is not being deployed.

This is breaking the arc-js tests.

(It is possible there are other issues that will show up in the alchemy demo, but I haven't been able to get the migration scripts to work there due to other breaking dependency changes.)

**Comment by dkent600** [comment]
Should arc be testing its migration script?

**Comment by orenyodfat** [comment]
arc-js test should not depend on 2_deploy_organization.js for testing or there reasons .

**Comment by dkent600** [comment]
> arc-js test should not depend on 2_deploy_organization.js for testing or there reasons

I don't understand why.  What is the alternative?

If the contracts are not properly deployed then Arc-js will not work properly.  Arc-js uses 2_deploy_organization.js to deploy contracts to m ainnet.  It includes 2_deploy_organization.js in the package for others to use to deploy to testnets.  We must confirm that the contract work.

In any case, unless something has changed, 2_deploy_organization.js needs to deploy TokenCapGC or a lot of stuff won't work.

**Comment by dkent600** [comment]
Sorry, though I don't see why this should have been closed, I unintentionally reopened it...

**Comment by orenyodfat** [comment]
arc-js should have its own deployment.
daostack-arc is not responsible for deployment or deployment scripts.
It is there just for testing and make sure we can an org deployment.
It just use test org 

const orgName = "TEST_ORGANIZATION";
const tokenName = "TestToken";
const tokenSymbol = "TST";

**Comment by dkent600** [comment]
> arc-js should have its own deployment.

I am nervous about this because the correct knowledge about *how* things should be deployed resides in arc and its team of experts, it seems to me.  Why would we ever want to have one version of 2_deploy_organization.js for arc and another one for arc-js?

> daostack-arc is not responsible for deployment or deployment scripts.

Then should 2_deploy_organization.js be excluded from the daostack-arc package?

**Comment by orenyodfat** [comment]
2_deploy_organization.js is on daostack-arc just to confirm and test the deployment needed for an arbitrary test organization.
not sure it needs to be removed from the daostack-arc package because it is parts of its tests.
(npm test).
The knowledge of how daostack org or any other org should looks like ,in terms of founders, schemes,reputation...and more.. is not in the scope of daostack-arc repo.

**Comment by dkent600** [comment]
A complication of that is that arc-js builds from the daostack-arc folder.  We currently rely on the migration information in arc's migrations folder.  If we are to ignore that folder, then we would need to do some work to effectively replace it.

**Comment by dkent600** [comment]
I note that the proposal to maintain deployed contract json files in the "node_modules/daostack-arc/build/contracts" folder, rather than a local "contracts" folder as I have done, would make less sense if arc contributes nothing but .sol files to the deployment.

**Comment by dkent600** [comment]
If this is the resolution, then we need to create an issue to make it happen in arc-js.

**Comment by dkent600** [comment]
@orenyodfat is currently working on how we are going to produce deployed contract.js files (in arc-js or a separate repo).

In the meantime, we need to come up with a working deployment script.  Either arc-js is going to have to roll its own, or arc will have to provide one, still to be decided.

**Comment by orenyodfat** [comment]
@dkent600 please change the issue title or close and open a new one.
is it a bug ?

**Comment by leviadam** [comment]
As @orenyodfat said. The deployment script on Arc is only for testing.
All deployments take place on Arc-js.
Arc-js should have its own migration script.
