### ISSUE TITLE
don't have configuration logic in solidity (but in javascript)

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#25]
General rule is that only those things that need to be persistent and trustless go to the blockchain/solidity. The reason is that the blockchain is expensive/difficult to work with, in comparison to javascript.

This seems to me a wrong pattern to use:
```
// deploy a helper contract that creates my controller
helpercontract = new GenesisSchema(configurationoptions)
// do some explicit stuff that the helpercontract is not doing automatically 
helpercontract.collectFoundershare()..
// now get the controller
controller = x.controller()
// if we need to do more config, we can do it by voting
controller.proposeToAddSomeSchema(0x1234, 400)
controller.voteonthis()

```
This is wrong because (1) configuration logic is spread over javascript and solidity, which is messy and hard to code and understand and (2) is wastes resources by deploying contracts that are just temporary helpers.

Instead, this pattern seems more straightforward to me:
```
// create a new Controller
controller = new Controller(somebasicsettings)
// the controller is owned by its cerateor, who can now do some more configutaation here in javascript
controller.setReputation(0x123, 100)
controller.addSchema(0x125)
// when configuration is done, the owner can renounce ownership
// (e.g. by setting the owner "to itself")
controller.transferOwnershipt(controller.address)
```

**Comment by yaronvel** [comment]
>General rule is that only those things that need to be persistent and trustless go to the blockchain/solidity. 

I agree. Main reason didn't do it was to have fast deployment (and I am rust in javascript).

But I don't agree on the details of your suggestion.
I don't think controller should have an owner. Only initial scheme.
In the genesis scheme we can have:
1) `scheme.init()`
2) `scheme.IniitController( name )`
3) `scheme.initialDistribution( merkleRoot )`

But this is not only a technical decision.
It is really a question of what is an organization?
At the current deployment organization is schemes.
And genesis scheme is the initial organization.

Also I don't like having `controller.transferOwnership` functions.

**Comment by jellegerbrandy** [comment]
Ok, the part about "genesis schema is the initial organization" I don't really get, and may also explain #29. Perhaps we can first discuss that, because it is more specific point, and perhaps easier to decide upon.

Regarding non-technical questions, the way I've been conceptualizing it,  "an organization"  is a family of interacting contracts (token, rep, controller, schemes). They are all held together by the controller, so if I' d be forced to designate a single contract as " the organization" , I'd take the controller.
