### ISSUE TITLE
GenesisScheme optimization

### ISSUE THREAD

**Issue by orenyodfat** [daostack/daostack#258]
- Mint founder's reputation before transfer ownership to the controller using reputation.setReputation .
- Mint founder's tokens before transfer ownership to the controller. 
This should save gas const on forging an org.

**Comment by dev-matan-tsuberi** [comment]
It's easy to do, but you'll lose the events `MintReputation` `MintTokens` (unless of course you make a function that just triggers the event and call it from the outside, but that's unreasonable).
I assume we can discard those initial token & reputation allocation events, right?
