### ISSUE TITLE
GenesisScheme is schizophrenic

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#29]
The genesischeme at the moment does two different, basically unrelated, things:

1) It serves to create a new controller (and has a getFoundershare method linked to that)
2) It serves as a schema to propose new schemas

I propose to separate this in two different contracts (or, if we do what i propse in #25, just forget about the 1), and just have it do 2).

**Comment by leviadam** [comment]
I think separating the two is reasonable.
Not sure if we have to, but modular architecture is a good thing.
