### ISSUE TITLE
check permissions when registering a new scheme in controller

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#45]
I.e. rewrite this line in `registerScheme`:

```   /* require(bytes4(15)&(_permissions^scheme.permissions)&(~schemes[msg.sender].permissions) == bytes4(0)); */ ```

**Comment by leviadam** [comment]
Hi @jellegerbrandy,

Can you tell what is the status with this issue?
In the code there is a comment:
```// XXX: Commented these next line as they led to errors and I cannot understand the code```

But the line is currently not commented and all tests are working.

**Comment by jellegerbrandy** [comment]
its a leftover i forgot and can be removed

**Comment by leviadam** [comment]
Done.
