### ISSUE TITLE
deploying a new organization takes a lot of work

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#47]
One of the main points of the genesisscheme is to simplify the deployment into as few transactions as possible. This is working out not so good.

At the moment of writing (commit 64c1554a003512c1cfc436040acc0bb114a13c8b) the deployment procedure of a new organization *that uses only already existing schemes* takes 8 different transactions, plus you need to have tokens to pay for registering your organization with the schemes (at the moment 3, possibly different from each other).

The relevant code is here: https://github.com/daostack/daostack/blob/64c1554a003512c1cfc436040acc0bb114a13c8b/lib/organization.js#L24

**Comment by jellegerbrandy** [comment]
(my personal opinion remains that this is a UX problem that should not be solved onchain. I.e. it is fine to have many transcations, we just need to hide the pain from the user by (1) checking all preconditions carefully before doing anything and (2) hide the fact that the transactions are many instead of just one.)

**Comment by leviadam** [comment]
I think at the moment we have much more important things, and we should indeed leave that to the UI.
