### ISSUE TITLE
linking schemes to controller

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#49]
Here's the thing:
 
In the library, I'd expect this kind of interaction (one of these, I'm not sure about the syntax yet):

    organization.proposeNewScheme(...) 
    organization.schemeRegistrar.proposeScheme(...)
    organization.schemes.schemeRegisterar.proposeScheme(...)

The first problem with this is that at the moment there is no way (as far as I can see) to get the 'schemeRegistrar' from the controller. 

There is an extra complication that in theory there is no *the* schemeRegistrar, there could be many registered.

(Just be clear, what we can do is:
 
  1. get SchemeRegister events for a controller
  1. get the addresses of the registered schemes from these events
  1. get the permissions and params of each registered scheme from the controller
  1. get info from the scheme instances themselves
)

Possible solutions:

  - add "type" to schemes mapping (makes registerScheme calls more complex)
  - add "type" property to each Scheme instance
  - add specific properties to the controller for `schemeRegistrar`, `updateScheme` and `globalConstraintRegistrar` (with specific registration functions). 

I vote tentatively for the second solution, which seems the least traumatic and does not need any changes in the code.

**Comment by jellegerbrandy** [comment]
I see now that I could derive the type of scheme from its permissions. I'll try that (but it is hacky)

**Comment by jellegerbrandy** [comment]
After talking to adam we'll do it lke this:

 - We know at which address our schemes are "officially deployed"
 - We keeep a list o fthese addresses with their associated interfaces in the library and use that

**Comment by leviadam** [comment]
I think this can be closed.
