### ISSUE TITLE
Decide on strategy to upgrade contracts

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#5]
Here's a lucid description of the (two) alternatives:
https://github.com/ConsenSys/smart-contract-best-practices#upgrading-broken-contracts

**Comment by jellegerbrandy** [comment]
Basically, "upgrading a contract" really means "deploying a new contract and make it so that all your users use the new contract".

As long as we control the UI, and no 3rd party is interfacing directly with the contract on the blockchain, this simple strategy is good enough:
 
- deploy new contract, "copying", if necessary, the data from the old contract
- update UI to reference new contract
- kill the old contract

A slightly more sophisticated form for this would be to have a "registry" contract on the blockchain that references the latest version (much like "example 1" in the consensys doc, or what truffle does)

**Comment by leviadam** [comment]
I think this issue can be closed now with the JS library notion.
