### ISSUE TITLE
proposal for changing registering of global constraints on controller

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#50]
No, each global contstraints on the controller are kept in an array of address of the global constraints. This makes it possible to only register each GC contract only once on the controller. But it is easy to think of scenarios in which we use the same GC contract for different constraints, using different params (e.ge. the tokenCap constraint can also be used for external tokens).

Propsal: instead, have an array of (gccontractaddres, params) structs (or some other kind of scheme)

**Comment by leviadam** [comment]
I think an array of a struct is a good solution.

**Comment by leviadam** [comment]
Done.
