### ISSUE TITLE
test SimpleVote.sol

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#51]
We need a set of tests (in `test/simplevote.js`) that test registering a prposal, voting with different parameters, testing permissions.

**Comment by leviadam** [comment]
Yap, how about @zuntah will try and do that?

**Comment by jellegerbrandy** [comment]
I wrote the basic workflow test in `test/simplevote.js`. There are still many edge cases to test (voting twice, canceling your vote, voting by the owner)

**Comment by leviadam** [comment]
I think we have enough tests for SimpleVote now.
