### ISSUE TITLE
Organization.new(..) API

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#55]
This is the currently implemented API, https://github.com/daostack/daostack/blob/dev/docs/library/organization.md

Here are some questions/suggestions for improvement:

 * Perhaps it is better to pass the founders like this:
    await  Organization.new({
      orgName: 'Name of organization', // string, required, name of organization
      tokenName: 'xx', // string, required, name of organization's token
      tokenSymbol: 'xxx', // string, required, symbol of organization's token
      founders: [
        address: '0x1234',
        reputatoin: 30,
        tokens: 12.3333,
     ] })

  *  should we offer the optino to set the schemes used. Or do we just offer our ones, or the possibility to "roll your own"?

**Comment by leviadam** [comment]
Hi @jellegerbrandy,

I don't really mind about the way we pass the founders.
About the scheme though, I think it is very important that we will allow for initial schemes.
Furthermore, I think we should also have that on the genesis contract, so it will only take a single transaction.

**Comment by jellegerbrandy** [comment]
ok, I adapted the documentation to reflect to founders thing.

wrt to the schemes, some more questions:

This is how we coudl pass the schemes to the constructor:

    Organization.new({ .....
        schemes: [
          {
            schemeType: 'UpgradeScheme',
            schemeParams: .... // 
            ..., // any other configuration params particular to this scheme
        },
          {
            schemeType: 'SchemeRegistrar',
            schemeParams: .... // 
            ..., // any other configuration params particular to this scheme
        },

another question: It would make sense that we can immediatly start using the schemes after constructing the org. But for that, we need to pay the fees to register these schemes. Which can be any ERC20 token, which we would need to buy. Two aproaches: we pay the fees (so that having the funds is a precondition for  creating the Org), or we pay the fees later (i.e. we register the schems without paying the fees). I vote for the first.

**Comment by leviadam** [comment]
I like the first as well. So it is decided.

**Comment by jellegerbrandy** [comment]
implemented as agreed, but it needs some more error handling for the fees.

**Comment by orenyodfat** [comment]
Is this can be moved to arc-js ?

**Comment by dkent600** [comment]
This is pretty much done except for the last comment about handling errors in fees.  There should be a fuller spec on that.  @leviadam  @orenyodfat @tibetsprague 

So I'd suggest we can close this and create a new one in arc-js, just on the fees bit, and being specific about the need.

**Comment by orenyodfat** [comment]
👍
