### ISSUE TITLE
SimpleVote semantics questions

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#58]
* `propose(...)` does not automatically vote, which is different from the `proposeScheme`, where proposing -does- imply voting.  

 * `vote(proposalId, yes, voter)`: the owner can cast a vote in the name of `voter`. This renders the contract inherently less "trustless" - trust is transferred to the owner. In our case, the owners is the controller: this means that the organization could accepts a proposal to vote in some minorityes name. It all seems messy and wrong. 

  * UX issue with SimpleProposal.vote(...) We now have the situation where, if the decisive vote is cast, the proposal is executed This has the following problem: if for some reason, the executions fails (and it could fail for many reasons), this means the vote will not be counted at all.

**Comment by jellegerbrandy** [comment]
personally, I'm for separating the functionality, i.e. "propose" proposes, and voting is done separately (as it is no in simplevote but not in schemeregistrar); and also to seperate 'vote(...)' from  `executeProposal`. 

Reasons are: the effet of this functions (and their cost) becomes very much dependent on (arbitrary) context, which makes it vulnerable to DOS attacks (I can stop you from voting by, say, spending the tokens we needed to execute the vote); the added complexitity is a seurity risk and makes code harder to read and debug; the functions have an ambiguous semantics ("vote" sometime smeans just casting your vote, sometimes means voting as well as doing other things)

The only reason I can think of for not doing that is UX - the fact that some wallets do not let you unlock the account but ask for confirmation on each transaction.

**Comment by leviadam** [comment]
This is indeed an issue.
I think the direction is indeed to separate.
We now have to build also another voting machine which will be more complex, but will have to have an a function called for execution. So I think doing so also with SimpleVote makes sense.
