### ISSUE TITLE
should SchemeRegistrar also register the controller at the scheme?

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#59]
The current workflow is to register the schem is:

 1. propose the Scheme
 2. vote for it
 3. deciding vote registers the scheme at the controller
 4. register the controller at the scheme
 5. start using it

Question: should 4. be included in 3? 
 
pro: easier to use, one transacion less
contra: possibily need tokens to register the controller

**Comment by jellegerbrandy** [comment]
I vote "yes"

**Comment by leviadam** [comment]
This means we need to build an interface for a universal scheme.
I think it is a good idea.

**Comment by leviadam** [comment]
Added the option for auto registration at scheme registrar.
Didn't want to touch ,much at the library, only added the parameter that needed to be sent to the function. At the moment I set it to `false`, so the registration in the library is still manual.

**Comment by leviadam** [comment]
Closing.
