### ISSUE TITLE
What's preventing a malicious Reputation's owner from manipulating proposal results?

### ISSUE THREAD

**Issue by assafmo** [daostack/daostack#67]
https://github.com/daostack/daostack/blob/6a2a928cc130e78638d4f440112e11c147f4b0b3/contracts/VotingMachines/SimpleVote.sol#L168

While a vote is opened, the `totalSupply` of `Reputation` can change. The owner of the Reputation is the only one that can mint and set reputation, but what happens when this owner cannot be trusted? He can manipulate `totalSupply` and affect voting results.

I think reputation should be given via contract and not by the Reputation `owner`.
E.g. make a reputation registry - like the gov registry - with "plug-able" reputation implementations and allow DOAs to create/choose their own reputation system.

Also I like that you did take into account that reputations change while a proposal is opened (by using `proposal.voted[_voter]`):
https://github.com/daostack/daostack/blob/6a2a928cc130e78638d4f440112e11c147f4b0b3/contracts/VotingMachines/SimpleVote.sol#L111-L120

**Comment by leviadam** [comment]
According to the architecture the owner of the reputation is a contract, the controller.

**Comment by jellegerbrandy** [comment]
I had meant to ask a question about that code you cited already when I saw it, so I'll just to it here. What is supposed to do? I can do this:

   1. have 10 rep
   2. vote yes (with my 10 rep). Vote will get registered.
   3. My rep changes, I have 12 now.
   4. vote again yes. Nothing will happen.
   5. vote no. (Vote will be be registered as -12)
   6. Vote yes again. (Vote will be registered ass +12)

This makes the behavior at (4) a bit pointless - we can  drop lines 112-118.

**Comment by leviadam** [comment]
5. is not correct. It will be -10.
I agree we can change it can be better so that re-voting can check is something changed, if yes, it will cancel the vote and re-vote.

**Comment by assafmo** [comment]
5 won't happen because of `proposal.voted[_voter] `.

**Comment by jellegerbrandy** [comment]
With this code, it seems to me that (5) _will_ happen: the code snippet above will call `cancelVote` and then the vote proceeds as normal. Let's write a test, though, instead of guessing what happens here :-)

**Comment by leviadam** [comment]
Jelle is right I think.
But tests are a good idea.

**Comment by assafmo** [comment]
Maybe I'll give it a go. It seems like a cool project with tons of potential. :smile:
