### ISSUE TITLE
Anyone can win their own proposed vote every time?

### ISSUE THREAD

**Issue by assafmo** [daostack/daostack#68]
Lets say we have a Reputation system with total supply 100 and I (`account[0]`) have a reputation of 5.

I can do:
```javascript
const simpleVote = await SimpleVote.new();
const executable = await ExecutableTest.new();
const paramsHash = await simpleVote.setParameters(reputation.address, 4);

const tx = await simpleVote.propose(paramsHash, helpers.NULL_ADDRESS, executable.address);
const proposalId = await getValueFromLogs(tx, '_proposalId');

await simpleVote.vote(proposalId, true, accounts[0]);
```

Won't this win every time?

**Comment by jellegerbrandy** [comment]
yes. You did not say why this is a problem,, though

**Comment by assafmo** [comment]
Because one person can propose new rules/schemes/global constraints as he pleased and accept the proposal by himself. The other reputation holders can't do anything to stop it.

**Comment by jellegerbrandy** [comment]
I don't think that is true. To propose a new scheme for a controller and get it accepted, you need to propose it via a schemeregistrar that is known by that controller. And that schemeregistrar willl only accepts proposals that need a certain majority (usually 50%).

**Comment by assafmo** [comment]
What is preventing me from accessing the Organization's `boolVote` field directly and executing the above code?

https://github.com/daostack/daostack/blob/baeb549095c624b3558a788d813b99ed506fbb9a/contracts/universalSchemes/GlobalConstraintRegistrar.sol#L26

**Comment by leviadam** [comment]
You have no access to change the organization boolVote.
The parameters are read from the controller itself.
