### ISSUE TITLE
Create Reputation Contract (step 3)

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/daostack#7]
* Contract initiated with fixed amount of non-transferable reputation score to deployer

* Assign new reputation score works like this:
  * open a Ballot for assigning new reputation (#12) 
  * have reputation owners vote
  * Result of vote is the reputation-weighted median (RWM) of votes (out of entire reputation) (#11)
  * execute the proposal (depends on #11)
* Assigning new tokens works in a way very similar to assigning reputation, just that it is another type of Ballot (#13)

**Comment by renoire** [comment]
Ok, so I am a complete novice in all this stuff, so I assume I have a right to ask a lot of silly questions. 
As far as I understand, in the contract "reputation" there should be something like this
     
function openVote(address _contributor, addresss _contribution) {
        BallotReputation ballotReputation = new BallotReputation(*this -- which stands for the contract address, address _contributor, addresss _contribution);
        assert (ballotReputation.executeWinningProposal() != success) {return "failed"}
        return "success";
    } 

and in BallotReputation something like this

Ballot(reputationContractAddress)
    {
 ...

        /* 
            here we get all the proposals already made by other users, or wee have a hardcoded set? 
            Also, here we wait for the current node, the owner of the contract, to make a decision (in a callback or something?)
            do we also kinda wait to get all the other decisions in the network, and only then start to calculate?
        */
}

So, my question means that I don't really understand what happens when the ballot contract is executed.

executeWinningProposal -- here new reputation is given to the contributor. Why should we give him tokens if there is a TokenBallot for that?

**Comment by jellegerbrandy** [comment]
The ticket is confusing, and I will adapt it. Also the "Ballot" and "proposal" terminology does not help very much (the code is adapted from a ethereum example, that is where the names come from)

Anyway, this is the idea (even if the code is not doing this yet):

- Any user can create a new Ballot.
- A "Ballot" represents a decision to make by a group of voters - it defines a number of "proposals", and it has a reference to a repuation contract where the voters and their reputation are defined, and it defines a function "executeProposal" (that could be any kind of function)
- For example, a ballot could be about "given 200 coins to Alex", and the "proposals" would be "0" and "1", and executeProposal would transfer the coins depending ont he outcome. Or it could be "how many rep shall we give to Alex?" and the "proposals" could be a range from 0 to 1000.
- If "executeProposal" distributes tokens or rep, it should be called by an account that has the permissions to do this - i.e. it has to be called by the reputation contract.
- Users can now vote by calling the Ballot contract. The ballot contract weighs their votes on the basis of their reputation in the reputation contract. Proposals are "uint" (i.e. they are integers), so we can take the median.

There are other ways of setting this up. This approach is pretty generic, and I like the fact that the votes are registered not on the repuation contract itself, but on the ballot contract. Given that, I am not completely sure this pattern is the best way.
