### ISSUE TITLE
Error: Invalid JSON RPC response: "" while testing

### ISSUE THREAD

**Issue by assafmo** [daostack/daostack#74]
`Error: Invalid JSON RPC response: ""`

This sometimes happens while testing and it has something to do with `testrpc` (the process dies? some account ran out of funds?).

E.g. https://travis-ci.org/daostack/daostack/builds/267344591

**Comment by leviadam** [comment]
Probably testrpc process died for some reason.

**Comment by leviadam** [comment]
Closing this issue.
