### ISSUE TITLE
Provide typescript "typings" and interfaces for the javascript library modules and contracts

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#87]
It would be great to provide typescript "typings" (d.ts) and interfaces for the javascript library modules and contracts, for use by typescript applications that are using the library.

**Comment by dkent600** [comment]
Thanks to @tibetsprague and #110 we now have a d.ts.  However it is missing a bunch of stuff and is thus breaking the Alchemy build.  I'm working on it....

**Comment by tibetsprague** [comment]
Thanks Doug, sorry to break your build. I'm curious how Alchemy was working with arc.js before if it requires typings?

**Comment by dkent600** [comment]
@tibetsprague  It didn't _require_ typings but began to use the d.ts after it was included.

**Comment by leviadam** [comment]
Can we close this issue?
