### ISSUE TITLE
Should Schemes provide a friendly name for themselves?

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#90]
We need to decide whether DAOs should provide a friendly name for themselves, a name that will be presented to application users.

**Comment by leviadam** [comment]
What is wrong with orgName?

**Comment by dkent600** [comment]
It has no spaces.  "SchemeRegistrar" instead of "Scheme Registrar".

**Comment by leviadam** [comment]
Are you asking about DAOs or about schemes?

**Comment by dkent600** [comment]
Oops, sorry, the title was wrong:  Schemes.

**Comment by leviadam** [comment]
So this might be in the .js files in the library.
But not on the blockchain.

**Comment by orenyodfat** [comment]
Should we move this issue to arc-js ?

**Comment by dkent600** [comment]
Yes.  Do you happen to know if there is a way to do that in GitHub, or must we create a whole new issue in arc-js?

**Comment by orenyodfat** [comment]
Not sure there is a built in tool..
but you can try this one : https://github.com/google/github-issue-mover

**Comment by dkent600** [comment]
Thanks @orenyodfat
