### ISSUE TITLE
Organization.proposeScheme should be completed or removed

### ISSUE THREAD

**Issue by dkent600** [daostack/daostack#98]
`Organization.proposeScheme` only supports a couple of schemes.  It should be completed (and refactored) or removed until it is complete.

**Comment by leviadam** [comment]
We have to refactor the whole thing. This is part of redesigning the package.
After we will work on the settings this will be the next step with @tibetsprague.

**Comment by dkent600** [comment]
I have written some code in Alchemy that could be moved over to Arc in this effort, though even at that, there is still a lot to do.

**Comment by dkent600** [comment]
I'm going to use this issue as a placeholder for creating javascript helper methods for all of the primary scheme functions.

**Comment by dkent600** [comment]
Fixed by #153
